# Welcome to Jekyll!

# Website settings
title: Data Analysis for Economics
description: Miloud Lacheheb's blog.
keywords: Miloud Lacheheb,R,blog,Python,github,
baseurl:  /homepage # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://miloulach.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /Jalpc/static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

theme: jekyll-theme-cayman
